### ISSUE TITLE
Error loading dependency. 

### ISSUE THREAD

**Issue by eniac314** [malaire/elm-dependencies-analyzer#4]
I am getting `ERROR: Failed to fetch Skinney/murmur3 2.0.8` when trying to load a elm.json containing a dependency for Skynney/murmur3. It's in the example too. 

I tried installing it via elm install, no problem.

**Comment by malaire** [comment]
The problem is that author has changed GitHub username so that package is no longer available under username `Skinney`.

`elm install` works for you because you have used that package before and so it's in your local cache. If you try to install it on other computer without elm cache, then it will fail.

Package has been re-published under new name [`robinheghan/murmur3`](https://package.elm-lang.org/packages/robinheghan/murmur3/latest) with version `1.0.0`.

**Comment by eniac314** [comment]
I see. Thank you.
